name: neverout
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0	
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.3
  flutter_dotenv: ^5.2.1
  google_fonts: ^6.2.1
  provider: ^6.1.2
  image_picker: ^1.1.2
  google_ml_kit: ^0.19.0 # For OCR
  tflite_flutter: ^0.11.0   # For TensorFlow Lite
  intl: ^0.20.1           # For date formatting
  shared_preferences: ^2.3.2  # For storing user preferences
  flutter_local_notifications: ^17.2.3 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/models/


